# Generated by Django 5.1.1 on 2024-10-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('age', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Возраст')),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
                ('health', models.CharField(max_length=100, verbose_name='Здоровье')),
                ('image', models.ImageField(blank=True, default='/media/images/default_image.jpg', null=True, upload_to='images/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Кот',
                'verbose_name_plural': 'Коты',
            },
        ),
    ]
