# Generated by Django 5.1.1 on 2024-10-02 13:47

import django_countries.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.CharField(max_length=100, verbose_name='Животное')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
                ('health', models.CharField(max_length=100, verbose_name='Здоровье')),
                ('image', models.ImageField(blank=True, default='/media/images/default_image.jpg', null=True, upload_to='images/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Питомец',
                'verbose_name_plural': 'Питомцы',
            },
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='+7', max_length=128, null=True, region=None, verbose_name='Номер телефона')),
                ('country', django_countries.fields.CountryField(blank=True, default='RU', max_length=2, null=True, verbose_name='Страна')),
                ('places', models.CharField(max_length=100, verbose_name='Количество мест в приюте')),
            ],
            options={
                'verbose_name': 'Питомец',
                'verbose_name_plural': 'Питомцы',
            },
        ),
        migrations.DeleteModel(
            name='Cat',
        ),
    ]
